/*
 * Twilio - Chat
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChatV2Service {
    /// The SID of the Account that created the resource
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// DEPRECATED
    #[serde(
        rename = "consumption_report_interval",
        skip_serializing_if = "Option::is_none"
    )]
    pub consumption_report_interval: Option<i32>,
    /// The RFC 2822 date and time in GMT when the resource was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The RFC 2822 date and time in GMT when the resource was last updated
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    /// The channel role assigned to a channel creator when they join a new channel
    #[serde(
        rename = "default_channel_creator_role_sid",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_channel_creator_role_sid: Option<String>,
    /// The channel role assigned to users when they are added to a channel
    #[serde(
        rename = "default_channel_role_sid",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_channel_role_sid: Option<String>,
    /// The service role assigned to users when they are added to the service
    #[serde(
        rename = "default_service_role_sid",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_service_role_sid: Option<String>,
    /// The string that you assigned to describe the resource
    #[serde(rename = "friendly_name", skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<String>,
    /// An object that describes the limits of the service instance
    #[serde(rename = "limits", skip_serializing_if = "Option::is_none")]
    pub limits: Option<serde_json::Value>,
    /// The absolute URLs of the Service's Channels, Roles, and Users
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
    /// The properties of the media that the service supports
    #[serde(rename = "media", skip_serializing_if = "Option::is_none")]
    pub media: Option<serde_json::Value>,
    /// The notification configuration for the Service instance
    #[serde(rename = "notifications", skip_serializing_if = "Option::is_none")]
    pub notifications: Option<serde_json::Value>,
    /// The number of times calls to the `post_webhook_url` will be retried
    #[serde(
        rename = "post_webhook_retry_count",
        skip_serializing_if = "Option::is_none"
    )]
    pub post_webhook_retry_count: Option<i32>,
    /// The URL for post-event webhooks
    #[serde(rename = "post_webhook_url", skip_serializing_if = "Option::is_none")]
    pub post_webhook_url: Option<String>,
    /// Count of times webhook will be retried in case of timeout or 429/503/504 HTTP responses
    #[serde(
        rename = "pre_webhook_retry_count",
        skip_serializing_if = "Option::is_none"
    )]
    pub pre_webhook_retry_count: Option<i32>,
    /// The webhook URL for pre-event webhooks
    #[serde(rename = "pre_webhook_url", skip_serializing_if = "Option::is_none")]
    pub pre_webhook_url: Option<String>,
    /// Whether the Reachability Indicator feature is enabled for this Service instance
    #[serde(
        rename = "reachability_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub reachability_enabled: Option<bool>,
    /// Whether the Message Consumption Horizon feature is enabled
    #[serde(
        rename = "read_status_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub read_status_enabled: Option<bool>,
    /// The unique string that identifies the resource
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    /// How long in seconds to wait before assuming the user is no longer typing
    #[serde(
        rename = "typing_indicator_timeout",
        skip_serializing_if = "Option::is_none"
    )]
    pub typing_indicator_timeout: Option<i32>,
    /// The absolute URL of the Service resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The list of webhook events that are enabled for this Service instance
    #[serde(rename = "webhook_filters", skip_serializing_if = "Option::is_none")]
    pub webhook_filters: Option<Vec<String>>,
    /// The HTTP method  to use for both PRE and POST webhooks
    #[serde(rename = "webhook_method", skip_serializing_if = "Option::is_none")]
    pub webhook_method: Option<String>,
}

impl ChatV2Service {
    pub fn new() -> ChatV2Service {
        ChatV2Service {
            account_sid: None,
            consumption_report_interval: None,
            date_created: None,
            date_updated: None,
            default_channel_creator_role_sid: None,
            default_channel_role_sid: None,
            default_service_role_sid: None,
            friendly_name: None,
            limits: None,
            links: None,
            media: None,
            notifications: None,
            post_webhook_retry_count: None,
            post_webhook_url: None,
            pre_webhook_retry_count: None,
            pre_webhook_url: None,
            reachability_enabled: None,
            read_status_enabled: None,
            sid: None,
            typing_indicator_timeout: None,
            url: None,
            webhook_filters: None,
            webhook_method: None,
        }
    }
}
