/*
 * Twilio - Autopilot
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AutopilotV1AssistantTaskTaskStatistics {
    /// The SID of the Account that created the resource
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The SID of the Assistant that is the parent of the Task associated with the resource
    #[serde(rename = "assistant_sid", skip_serializing_if = "Option::is_none")]
    pub assistant_sid: Option<String>,
    /// The total number of Fields associated with the Task
    #[serde(rename = "fields_count", skip_serializing_if = "Option::is_none")]
    pub fields_count: Option<i32>,
    /// The total number of Samples associated with the Task
    #[serde(rename = "samples_count", skip_serializing_if = "Option::is_none")]
    pub samples_count: Option<i32>,
    /// The SID of the Task for which the statistics were collected
    #[serde(rename = "task_sid", skip_serializing_if = "Option::is_none")]
    pub task_sid: Option<String>,
    /// The absolute URL of the TaskStatistics resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl AutopilotV1AssistantTaskTaskStatistics {
    pub fn new() -> AutopilotV1AssistantTaskTaskStatistics {
        AutopilotV1AssistantTaskTaskStatistics {
            account_sid: None,
            assistant_sid: None,
            fields_count: None,
            samples_count: None,
            task_sid: None,
            url: None,
        }
    }
}


