/*
 * Twilio - Bulkexports
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkexportsV1ExportDayInstance {
    #[serde(rename = "redirect_to", skip_serializing_if = "Option::is_none")]
    pub redirect_to: Option<String>,
}

impl BulkexportsV1ExportDayInstance {
    pub fn new() -> BulkexportsV1ExportDayInstance {
        BulkexportsV1ExportDayInstance { redirect_to: None }
    }
}
