/*
 * Twilio - Bulkexports
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkexportsV1ExportDay {
    /// The date when resource is created
    #[serde(rename = "create_date", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    /// The date of the data in the file
    #[serde(rename = "day", skip_serializing_if = "Option::is_none")]
    pub day: Option<String>,
    /// The friendly name specified when creating the job
    #[serde(rename = "friendly_name", skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<String>,
    /// The type of communication – Messages, Calls, Conferences, and Participants
    #[serde(rename = "resource_type", skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<String>,
    /// Size of the file in bytes
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
}

impl BulkexportsV1ExportDay {
    pub fn new() -> BulkexportsV1ExportDay {
        BulkexportsV1ExportDay {
            create_date: None,
            day: None,
            friendly_name: None,
            resource_type: None,
            size: None,
        }
    }
}
