/*
 * Twilio - Conversations
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConversationsV1ConfigurationConfigurationWebhook {
    /// The unique ID of the Account responsible for this conversation.
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The list of webhook event triggers that are enabled for this Service.
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<String>>,
    /// The HTTP method to be used when sending a webhook request.
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<Method>,
    /// The absolute url the post-event webhook request should be sent to.
    #[serde(rename = "post_webhook_url", skip_serializing_if = "Option::is_none")]
    pub post_webhook_url: Option<String>,
    /// The absolute url the pre-event webhook request should be sent to.
    #[serde(rename = "pre_webhook_url", skip_serializing_if = "Option::is_none")]
    pub pre_webhook_url: Option<String>,
    /// The routing target of the webhook.
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Target>,
    /// An absolute URL for this webhook.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl ConversationsV1ConfigurationConfigurationWebhook {
    pub fn new() -> ConversationsV1ConfigurationConfigurationWebhook {
        ConversationsV1ConfigurationConfigurationWebhook {
            account_sid: None,
            filters: None,
            method: None,
            post_webhook_url: None,
            pre_webhook_url: None,
            target: None,
            url: None,
        }
    }
}

/// The HTTP method to be used when sending a webhook request.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "GET")]
    GET,
    #[serde(rename = "POST")]
    POST,
}
/// The routing target of the webhook.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Target {
    #[serde(rename = "webhook")]
    Webhook,
    #[serde(rename = "flex")]
    Flex,
}

