/*
 * Twilio - Conversations
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListServiceBindingResponse {
    #[serde(rename = "bindings", skip_serializing_if = "Option::is_none")]
    pub bindings: Option<Vec<crate::models::ConversationsV1ServiceServiceBinding>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListConversationResponseMeta>>,
}

impl ListServiceBindingResponse {
    pub fn new() -> ListServiceBindingResponse {
        ListServiceBindingResponse {
            bindings: None,
            meta: None,
        }
    }
}


