/*
 * Twilio - Monitor
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MonitorV1AlertInstance {
    /// The SID of the Account that created the resource
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The text of the alert
    #[serde(rename = "alert_text", skip_serializing_if = "Option::is_none")]
    pub alert_text: Option<String>,
    /// The API version used when the alert was generated
    #[serde(rename = "api_version", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    /// The ISO 8601 date and time in GMT when the resource was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The date and time when the alert was generated specified in ISO 8601 format
    #[serde(rename = "date_generated", skip_serializing_if = "Option::is_none")]
    pub date_generated: Option<String>,
    /// The ISO 8601 date and time in GMT when the resource was last updated
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    /// The error code for the condition that generated the alert
    #[serde(rename = "error_code", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
    /// The log level
    #[serde(rename = "log_level", skip_serializing_if = "Option::is_none")]
    pub log_level: Option<String>,
    /// The URL of the page in our Error Dictionary with more information about the error condition
    #[serde(rename = "more_info", skip_serializing_if = "Option::is_none")]
    pub more_info: Option<String>,
    /// The request headers of the request that generated the alert
    #[serde(rename = "request_headers", skip_serializing_if = "Option::is_none")]
    pub request_headers: Option<String>,
    /// The method used by the request that generated the alert
    #[serde(rename = "request_method", skip_serializing_if = "Option::is_none")]
    pub request_method: Option<RequestMethod>,
    /// The URL of the request that generated the alert
    #[serde(rename = "request_url", skip_serializing_if = "Option::is_none")]
    pub request_url: Option<String>,
    /// The variables passed in the request that generated the alert
    #[serde(rename = "request_variables", skip_serializing_if = "Option::is_none")]
    pub request_variables: Option<String>,
    /// The SID of the resource for which the alert was generated
    #[serde(rename = "resource_sid", skip_serializing_if = "Option::is_none")]
    pub resource_sid: Option<String>,
    /// The response body of the request that generated the alert
    #[serde(rename = "response_body", skip_serializing_if = "Option::is_none")]
    pub response_body: Option<String>,
    /// The response headers of the request that generated the alert
    #[serde(rename = "response_headers", skip_serializing_if = "Option::is_none")]
    pub response_headers: Option<String>,
    /// The SID of the service or resource that generated the alert
    #[serde(rename = "service_sid", skip_serializing_if = "Option::is_none")]
    pub service_sid: Option<String>,
    /// The unique string that identifies the resource
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    /// The absolute URL of the Alert resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl MonitorV1AlertInstance {
    pub fn new() -> MonitorV1AlertInstance {
        MonitorV1AlertInstance {
            account_sid: None,
            alert_text: None,
            api_version: None,
            date_created: None,
            date_generated: None,
            date_updated: None,
            error_code: None,
            log_level: None,
            more_info: None,
            request_headers: None,
            request_method: None,
            request_url: None,
            request_variables: None,
            resource_sid: None,
            response_body: None,
            response_headers: None,
            service_sid: None,
            sid: None,
            url: None,
        }
    }
}

/// The method used by the request that generated the alert
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestMethod {
    #[serde(rename = "HEAD")]
    HEAD,
    #[serde(rename = "GET")]
    GET,
    #[serde(rename = "POST")]
    POST,
    #[serde(rename = "PATCH")]
    PATCH,
    #[serde(rename = "PUT")]
    PUT,
    #[serde(rename = "DELETE")]
    DELETE,
}
