/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.2
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListBucketResponse {
    #[serde(rename = "buckets", skip_serializing_if = "Option::is_none")]
    pub buckets: Option<Vec<crate::models::VerifyV2ServiceRateLimitBucket>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListVerificationAttemptResponseMeta>>,
}

impl ListBucketResponse {
    pub fn new() -> ListBucketResponse {
        ListBucketResponse {
            buckets: None,
            meta: None,
        }
    }
}


