/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListVerificationAttemptResponse {
    #[serde(rename = "attempts", skip_serializing_if = "Option::is_none")]
    pub attempts: Option<Vec<crate::models::VerifyV2VerificationAttempt>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListVerificationAttemptResponseMeta>>,
}

impl ListVerificationAttemptResponse {
    pub fn new() -> ListVerificationAttemptResponse {
        ListVerificationAttemptResponse {
            attempts: None,
            meta: None,
        }
    }
}
