/*
 * Twilio - Verify
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VerifyV2ServiceEntityChallengeNotification {
    /// Account Sid.
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// Challenge Sid.
    #[serde(rename = "challenge_sid", skip_serializing_if = "Option::is_none")]
    pub challenge_sid: Option<String>,
    /// The date this Notification was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// Entity Sid.
    #[serde(rename = "entity_sid", skip_serializing_if = "Option::is_none")]
    pub entity_sid: Option<String>,
    /// Unique external identifier of the Entity
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<String>,
    /// The priority of the notification.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<String>,
    /// Service Sid.
    #[serde(rename = "service_sid", skip_serializing_if = "Option::is_none")]
    pub service_sid: Option<String>,
    /// A string that uniquely identifies this Notification.
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    /// How long, in seconds, the notification is valid.
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
}

impl VerifyV2ServiceEntityChallengeNotification {
    pub fn new() -> VerifyV2ServiceEntityChallengeNotification {
        VerifyV2ServiceEntityChallengeNotification {
            account_sid: None,
            challenge_sid: None,
            date_created: None,
            entity_sid: None,
            identity: None,
            priority: None,
            service_sid: None,
            sid: None,
            ttl: None,
        }
    }
}


