/*
 * Twilio - Numbers
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NumbersV2RegulatoryComplianceBundleItemAssignment {
    /// The SID of the Account that created the resource
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The unique string that identifies the Bundle resource.
    #[serde(rename = "bundle_sid", skip_serializing_if = "Option::is_none")]
    pub bundle_sid: Option<String>,
    /// The ISO 8601 date and time in GMT when the resource was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The sid of an object bag
    #[serde(rename = "object_sid", skip_serializing_if = "Option::is_none")]
    pub object_sid: Option<String>,
    /// The unique string that identifies the resource
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    /// The absolute URL of the Identity resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl NumbersV2RegulatoryComplianceBundleItemAssignment {
    pub fn new() -> NumbersV2RegulatoryComplianceBundleItemAssignment {
        NumbersV2RegulatoryComplianceBundleItemAssignment {
            account_sid: None,
            bundle_sid: None,
            date_created: None,
            object_sid: None,
            sid: None,
            url: None,
        }
    }
}


