/*
 * Twilio - Lookups
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LookupsV1PhoneNumber {
    /// A JSON string with the results of the Add-ons you specified
    #[serde(rename = "add_ons", skip_serializing_if = "Option::is_none")]
    pub add_ons: Option<serde_json::Value>,
    /// The name of the phone number's owner
    #[serde(rename = "caller_name", skip_serializing_if = "Option::is_none")]
    pub caller_name: Option<serde_json::Value>,
    /// The telecom company that provides the phone number
    #[serde(rename = "carrier", skip_serializing_if = "Option::is_none")]
    pub carrier: Option<serde_json::Value>,
    /// The ISO country code for the phone number
    #[serde(rename = "country_code", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    /// The phone number, in national format
    #[serde(rename = "national_format", skip_serializing_if = "Option::is_none")]
    pub national_format: Option<String>,
    /// The phone number in E.164 format
    #[serde(rename = "phone_number", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    /// The absolute URL of the resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl LookupsV1PhoneNumber {
    pub fn new() -> LookupsV1PhoneNumber {
        LookupsV1PhoneNumber {
            add_ons: None,
            caller_name: None,
            carrier: None,
            country_code: None,
            national_format: None,
            phone_number: None,
            url: None,
        }
    }
}
