/*
 * Twilio - Taskrouter
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListWorkerResponse {
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListWorkspaceResponseMeta>>,
    #[serde(rename = "workers", skip_serializing_if = "Option::is_none")]
    pub workers: Option<Vec<crate::models::TaskrouterV1WorkspaceWorker>>,
}

impl ListWorkerResponse {
    pub fn new() -> ListWorkerResponse {
        ListWorkerResponse {
            meta: None,
            workers: None,
        }
    }
}


