/*
 * Twilio - Events
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EventsV1SinkSinkValidate {
    /// Feedback indicating whether the given Sink was validated.
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl EventsV1SinkSinkValidate {
    pub fn new() -> EventsV1SinkSinkValidate {
        EventsV1SinkSinkValidate {
            result: None,
        }
    }
}


