/*
 * Twilio - Events
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EventsV1SubscriptionSubscribedEvent {
    /// Account SID.
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The schema version that the subscription should use.
    #[serde(rename = "schema_version", skip_serializing_if = "Option::is_none")]
    pub schema_version: Option<i32>,
    /// Subscription SID.
    #[serde(rename = "subscription_sid", skip_serializing_if = "Option::is_none")]
    pub subscription_sid: Option<String>,
    /// Type of event being subscribed to.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,
    /// The URL of this resource.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl EventsV1SubscriptionSubscribedEvent {
    pub fn new() -> EventsV1SubscriptionSubscribedEvent {
        EventsV1SubscriptionSubscribedEvent {
            account_sid: None,
            schema_version: None,
            subscription_sid: None,
            type_: None,
            url: None,
        }
    }
}
