/*
 * Twilio - Proxy
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListMessageInteractionResponse {
    #[serde(rename = "interactions", skip_serializing_if = "Option::is_none")]
    pub interactions:
        Option<Vec<crate::models::ProxyV1ServiceSessionParticipantMessageInteraction>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListServiceResponseMeta>>,
}

impl ListMessageInteractionResponse {
    pub fn new() -> ListMessageInteractionResponse {
        ListMessageInteractionResponse {
            interactions: None,
            meta: None,
        }
    }
}
