/*
 * Twilio - Proxy
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProxyV1ServiceShortCode {
    /// The SID of the Account that created the resource
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    #[serde(rename = "capabilities", skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<Box<crate::models::ProxyV1ServiceShortCodeCapabilities>>,
    /// The ISO 8601 date and time in GMT when the resource was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The ISO 8601 date and time in GMT when the resource was last updated
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    /// Whether the short code should be reserved for manual assignment to participants only
    #[serde(rename = "is_reserved", skip_serializing_if = "Option::is_none")]
    pub is_reserved: Option<bool>,
    /// The ISO Country Code
    #[serde(rename = "iso_country", skip_serializing_if = "Option::is_none")]
    pub iso_country: Option<String>,
    /// The SID of the resource's parent Service
    #[serde(rename = "service_sid", skip_serializing_if = "Option::is_none")]
    pub service_sid: Option<String>,
    /// The short code's number
    #[serde(rename = "short_code", skip_serializing_if = "Option::is_none")]
    pub short_code: Option<String>,
    /// The unique string that identifies the resource
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    /// The absolute URL of the ShortCode resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl ProxyV1ServiceShortCode {
    pub fn new() -> ProxyV1ServiceShortCode {
        ProxyV1ServiceShortCode {
            account_sid: None,
            capabilities: None,
            date_created: None,
            date_updated: None,
            is_reserved: None,
            iso_country: None,
            service_sid: None,
            short_code: None,
            sid: None,
            url: None,
        }
    }
}
