/*
 * Twilio - Studio
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.2
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListFlowResponse {
    #[serde(rename = "flows", skip_serializing_if = "Option::is_none")]
    pub flows: Option<Vec<crate::models::StudioV2Flow>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListFlowResponseMeta>>,
}

impl ListFlowResponse {
    pub fn new() -> ListFlowResponse {
        ListFlowResponse {
            flows: None,
            meta: None,
        }
    }
}


