/*
 * Twilio - Flex
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.2
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FlexV1Channel {
    /// The SID of the Account that created the resource and owns this Workflow
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The ISO 8601 date and time in GMT when the Flex chat channel was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The ISO 8601 date and time in GMT when the Flex chat channel was last updated
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    /// The SID of the Flex Flow
    #[serde(rename = "flex_flow_sid", skip_serializing_if = "Option::is_none")]
    pub flex_flow_sid: Option<String>,
    /// The unique string that identifies the resource
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    /// The SID of the TaskRouter Task
    #[serde(rename = "task_sid", skip_serializing_if = "Option::is_none")]
    pub task_sid: Option<String>,
    /// The absolute URL of the Flex chat channel resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The SID of the chat user
    #[serde(rename = "user_sid", skip_serializing_if = "Option::is_none")]
    pub user_sid: Option<String>,
}

impl FlexV1Channel {
    pub fn new() -> FlexV1Channel {
        FlexV1Channel {
            account_sid: None,
            date_created: None,
            date_updated: None,
            flex_flow_sid: None,
            sid: None,
            task_sid: None,
            url: None,
            user_sid: None,
        }
    }
}


