/*
 * Twilio - Pricing
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PricingV2TrunkingCountryInstanceTerminatingPrefixPrices {
    #[serde(rename = "base_price", skip_serializing_if = "Option::is_none")]
    pub base_price: Option<f32>,
    #[serde(rename = "current_price", skip_serializing_if = "Option::is_none")]
    pub current_price: Option<f32>,
    #[serde(
        rename = "destination_prefixes",
        skip_serializing_if = "Option::is_none"
    )]
    pub destination_prefixes: Option<Vec<String>>,
    #[serde(rename = "friendly_name", skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<String>,
    #[serde(
        rename = "origination_prefixes",
        skip_serializing_if = "Option::is_none"
    )]
    pub origination_prefixes: Option<Vec<String>>,
}

impl PricingV2TrunkingCountryInstanceTerminatingPrefixPrices {
    pub fn new() -> PricingV2TrunkingCountryInstanceTerminatingPrefixPrices {
        PricingV2TrunkingCountryInstanceTerminatingPrefixPrices {
            base_price: None,
            current_price: None,
            destination_prefixes: None,
            friendly_name: None,
            origination_prefixes: None,
        }
    }
}
