/*
 * Twilio - Pricing
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

/// PricingV2VoiceVoiceNumberInboundCallPrice : The InboundCallPrice record



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PricingV2VoiceVoiceNumberInboundCallPrice {
    #[serde(rename = "base_price", skip_serializing_if = "Option::is_none")]
    pub base_price: Option<f32>,
    #[serde(rename = "current_price", skip_serializing_if = "Option::is_none")]
    pub current_price: Option<f32>,
    #[serde(rename = "number_type", skip_serializing_if = "Option::is_none")]
    pub number_type: Option<String>,
}

impl PricingV2VoiceVoiceNumberInboundCallPrice {
    /// The InboundCallPrice record
    pub fn new() -> PricingV2VoiceVoiceNumberInboundCallPrice {
        PricingV2VoiceVoiceNumberInboundCallPrice {
            base_price: None,
            current_price: None,
            number_type: None,
        }
    }
}


