/*
 * Twilio - Sync
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.2
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SyncV1ServiceSyncListSyncListItem {
    /// The SID of the Account that created the resource
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The identity of the List Item's creator
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    /// An arbitrary, schema-less object that the List Item stores
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// The ISO 8601 date and time in GMT when the resource was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The ISO 8601 date and time in GMT when the List Item expires
    #[serde(rename = "date_expires", skip_serializing_if = "Option::is_none")]
    pub date_expires: Option<String>,
    /// The ISO 8601 date and time in GMT when the resource was last updated
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    /// The automatically generated index of the List Item
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<i32>,
    /// The SID of the Sync List that contains the List Item
    #[serde(rename = "list_sid", skip_serializing_if = "Option::is_none")]
    pub list_sid: Option<String>,
    /// The current revision of the item, represented as a string
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    /// The SID of the Sync Service that the resource is associated with
    #[serde(rename = "service_sid", skip_serializing_if = "Option::is_none")]
    pub service_sid: Option<String>,
    /// The absolute URL of the List Item resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl SyncV1ServiceSyncListSyncListItem {
    pub fn new() -> SyncV1ServiceSyncListSyncListItem {
        SyncV1ServiceSyncListSyncListItem {
            account_sid: None,
            created_by: None,
            data: None,
            date_created: None,
            date_expires: None,
            date_updated: None,
            index: None,
            list_sid: None,
            revision: None,
            service_sid: None,
            url: None,
        }
    }
}


