/*
 * Twilio - Serverless
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListBuildResponse {
    #[serde(rename = "builds", skip_serializing_if = "Option::is_none")]
    pub builds: Option<Vec<crate::models::ServerlessV1ServiceBuild>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListServiceResponseMeta>>,
}

impl ListBuildResponse {
    pub fn new() -> ListBuildResponse {
        ListBuildResponse {
            builds: None,
            meta: None,
        }
    }
}
