/*
 * Twilio - Serverless
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.2
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAssetVersionResponse {
    #[serde(rename = "asset_versions", skip_serializing_if = "Option::is_none")]
    pub asset_versions: Option<Vec<crate::models::ServerlessV1ServiceAssetAssetVersion>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListServiceResponseMeta>>,
}

impl ListAssetVersionResponse {
    pub fn new() -> ListAssetVersionResponse {
        ListAssetVersionResponse {
            asset_versions: None,
            meta: None,
        }
    }
}


