/*
 * Twilio - Serverless
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServerlessV1ServiceEnvironment {
    /// The SID of the Account that created the Environment resource
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The SID of the build deployed in the environment
    #[serde(rename = "build_sid", skip_serializing_if = "Option::is_none")]
    pub build_sid: Option<String>,
    /// The ISO 8601 date and time in GMT when the Environment resource was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The ISO 8601 date and time in GMT when the Environment resource was last updated
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    /// The base domain name for all Functions and Assets deployed in the Environment
    #[serde(rename = "domain_name", skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<String>,
    /// A URL-friendly name that represents the environment
    #[serde(rename = "domain_suffix", skip_serializing_if = "Option::is_none")]
    pub domain_suffix: Option<String>,
    /// The URLs of the Environment resource's nested resources
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
    /// The SID of the Service that the Environment resource is associated with
    #[serde(rename = "service_sid", skip_serializing_if = "Option::is_none")]
    pub service_sid: Option<String>,
    /// The unique string that identifies the Environment resource
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    /// A user-defined string that uniquely identifies the Environment resource
    #[serde(rename = "unique_name", skip_serializing_if = "Option::is_none")]
    pub unique_name: Option<String>,
    /// The absolute URL of the Environment resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl ServerlessV1ServiceEnvironment {
    pub fn new() -> ServerlessV1ServiceEnvironment {
        ServerlessV1ServiceEnvironment {
            account_sid: None,
            build_sid: None,
            date_created: None,
            date_updated: None,
            domain_name: None,
            domain_suffix: None,
            links: None,
            service_sid: None,
            sid: None,
            unique_name: None,
            url: None,
        }
    }
}


