/*
 * Twilio - Accounts
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListCredentialAwsResponse {
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Vec<crate::models::AccountsV1CredentialCredentialAws>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListCredentialAwsResponseMeta>>,
}

impl ListCredentialAwsResponse {
    pub fn new() -> ListCredentialAwsResponse {
        ListCredentialAwsResponse {
            credentials: None,
            meta: None,
        }
    }
}
