/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiV2010AccountCallCallEvent {
    /// Call Request.
    #[serde(rename = "request", skip_serializing_if = "Option::is_none")]
    pub request: Option<serde_json::Value>,
    /// Call Response with Events.
    #[serde(rename = "response", skip_serializing_if = "Option::is_none")]
    pub response: Option<serde_json::Value>,
}

impl ApiV2010AccountCallCallEvent {
    pub fn new() -> ApiV2010AccountCallCallEvent {
        ApiV2010AccountCallCallEvent {
            request: None,
            response: None,
        }
    }
}
