/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiV2010AccountCallCallFeedback {
    /// The unique sid that identifies this account
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The date this resource was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The date this resource was last updated
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    /// Issues experienced during the call
    #[serde(rename = "issues", skip_serializing_if = "Option::is_none")]
    pub issues: Option<Vec<Issues>>,
    /// 1 to 5 quality score
    #[serde(rename = "quality_score", skip_serializing_if = "Option::is_none")]
    pub quality_score: Option<i32>,
    /// A string that uniquely identifies this feedback resource
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
}

impl ApiV2010AccountCallCallFeedback {
    pub fn new() -> ApiV2010AccountCallCallFeedback {
        ApiV2010AccountCallCallFeedback {
            account_sid: None,
            date_created: None,
            date_updated: None,
            issues: None,
            quality_score: None,
            sid: None,
        }
    }
}

/// Issues experienced during the call
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Issues {
    #[serde(rename = "audio-latency")]
    AudioLatency,
    #[serde(rename = "digits-not-captured")]
    DigitsNotCaptured,
    #[serde(rename = "dropped-call")]
    DroppedCall,
    #[serde(rename = "imperfect-audio")]
    ImperfectAudio,
    #[serde(rename = "incorrect-caller-id")]
    IncorrectCallerId,
    #[serde(rename = "one-way-audio")]
    OneWayAudio,
    #[serde(rename = "post-dial-delay")]
    PostDialDelay,
    #[serde(rename = "unsolicited-call")]
    UnsolicitedCall,
}
