/*
 * Twilio - Messaging
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.2
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAlphaSenderResponse {
    #[serde(rename = "alpha_senders", skip_serializing_if = "Option::is_none")]
    pub alpha_senders: Option<Vec<crate::models::MessagingV1ServiceAlphaSender>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListServiceResponseMeta>>,
}

impl ListAlphaSenderResponse {
    pub fn new() -> ListAlphaSenderResponse {
        ListAlphaSenderResponse {
            alpha_senders: None,
            meta: None,
        }
    }
}


