/*
 * Twilio - Video
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.2
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VideoV1RecordingSettings {
    /// The SID of the Account that created the resource
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The SID of the stored Credential resource
    #[serde(rename = "aws_credentials_sid", skip_serializing_if = "Option::is_none")]
    pub aws_credentials_sid: Option<String>,
    /// The URL of the AWS S3 bucket where the recordings are stored
    #[serde(rename = "aws_s3_url", skip_serializing_if = "Option::is_none")]
    pub aws_s3_url: Option<String>,
    /// Whether all recordings are written to the aws_s3_url
    #[serde(rename = "aws_storage_enabled", skip_serializing_if = "Option::is_none")]
    pub aws_storage_enabled: Option<bool>,
    /// Whether all recordings are stored in an encrypted form
    #[serde(rename = "encryption_enabled", skip_serializing_if = "Option::is_none")]
    pub encryption_enabled: Option<bool>,
    /// The SID of the Public Key resource used for encryption
    #[serde(rename = "encryption_key_sid", skip_serializing_if = "Option::is_none")]
    pub encryption_key_sid: Option<String>,
    /// The string that you assigned to describe the resource
    #[serde(rename = "friendly_name", skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<String>,
    /// The absolute URL of the resource
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl VideoV1RecordingSettings {
    pub fn new() -> VideoV1RecordingSettings {
        VideoV1RecordingSettings {
            account_sid: None,
            aws_credentials_sid: None,
            aws_s3_url: None,
            aws_storage_enabled: None,
            encryption_enabled: None,
            encryption_key_sid: None,
            friendly_name: None,
            url: None,
        }
    }
}


