/*
 * Twilio - Video
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.2
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VideoV1RoomRoomRecordingRuleRules {
    #[serde(rename = "all", skip_serializing_if = "Option::is_none")]
    pub all: Option<bool>,
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "publisher", skip_serializing_if = "Option::is_none")]
    pub publisher: Option<String>,
    #[serde(rename = "track", skip_serializing_if = "Option::is_none")]
    pub track: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl VideoV1RoomRoomRecordingRuleRules {
    pub fn new() -> VideoV1RoomRoomRecordingRuleRules {
        VideoV1RoomRoomRecordingRuleRules {
            all: None,
            kind: None,
            publisher: None,
            track: None,
            _type: None,
        }
    }
}


