/*
 * Twilio - Trunking
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListIpAccessControlListResponse {
    #[serde(
        rename = "ip_access_control_lists",
        skip_serializing_if = "Option::is_none"
    )]
    pub ip_access_control_lists: Option<Vec<crate::models::TrunkingV1TrunkIpAccessControlList>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListTrunkResponseMeta>>,
}

impl ListIpAccessControlListResponse {
    pub fn new() -> ListIpAccessControlListResponse {
        ListIpAccessControlListResponse {
            ip_access_control_lists: None,
            meta: None,
        }
    }
}
