/*
 * Twilio - Supersim
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.2
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListBillingPeriodResponse {
    #[serde(rename = "billing_periods", skip_serializing_if = "Option::is_none")]
    pub billing_periods: Option<Vec<crate::models::SupersimV1SimBillingPeriod>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListCommandResponseMeta>>,
}

impl ListBillingPeriodResponse {
    pub fn new() -> ListBillingPeriodResponse {
        ListBillingPeriodResponse {
            billing_periods: None,
            meta: None,
        }
    }
}


