/*
 * Twilio - Supersim
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SupersimV1UsageRecord {
    /// The SID of the Account that incurred the usage.
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// Total data downloaded in bytes, aggregated by the query parameters.
    #[serde(rename = "data_download", skip_serializing_if = "Option::is_none")]
    pub data_download: Option<i32>,
    /// Total of data_upload and data_download.
    #[serde(rename = "data_total", skip_serializing_if = "Option::is_none")]
    pub data_total: Option<i32>,
    /// Total data uploaded in bytes, aggregated by the query parameters.
    #[serde(rename = "data_upload", skip_serializing_if = "Option::is_none")]
    pub data_upload: Option<i32>,
    /// SID of the Fleet resource on which the usage occurred.
    #[serde(rename = "fleet_sid", skip_serializing_if = "Option::is_none")]
    pub fleet_sid: Option<String>,
    /// Alpha-2 ISO Country Code of the country the usage occurred in.
    #[serde(rename = "iso_country", skip_serializing_if = "Option::is_none")]
    pub iso_country: Option<String>,
    /// SID of the Network resource on which the usage occurred.
    #[serde(rename = "network_sid", skip_serializing_if = "Option::is_none")]
    pub network_sid: Option<String>,
    /// The time period for which the usage is reported.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<serde_json::Value>,
    /// SID of a Sim resource to which the UsageRecord belongs.
    #[serde(rename = "sim_sid", skip_serializing_if = "Option::is_none")]
    pub sim_sid: Option<String>,
}

impl SupersimV1UsageRecord {
    pub fn new() -> SupersimV1UsageRecord {
        SupersimV1UsageRecord {
            account_sid: None,
            data_download: None,
            data_total: None,
            data_upload: None,
            fleet_sid: None,
            iso_country: None,
            network_sid: None,
            period: None,
            sim_sid: None,
        }
    }
}


