/*
 * Twilio - Supersim
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.20.2
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SupersimV1SimBillingPeriod {
    /// The SID of the Account the Super SIM belongs to
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The ISO 8601 date and time in GMT when the resource was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The ISO 8601 date and time in GMT when the resource was last updated
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    /// The end time of the Billing Period
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    /// The type of the Billing Period
    #[serde(rename = "period_type", skip_serializing_if = "Option::is_none")]
    pub period_type: Option<PeriodType>,
    /// The SID of the Billing Period
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    /// The SID of the Super SIM the Billing Period belongs to
    #[serde(rename = "sim_sid", skip_serializing_if = "Option::is_none")]
    pub sim_sid: Option<String>,
    /// The start time of the Billing Period
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
}

impl SupersimV1SimBillingPeriod {
    pub fn new() -> SupersimV1SimBillingPeriod {
        SupersimV1SimBillingPeriod {
            account_sid: None,
            date_created: None,
            date_updated: None,
            end_time: None,
            period_type: None,
            sid: None,
            sim_sid: None,
            start_time: None,
        }
    }
}

/// The type of the Billing Period
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PeriodType {
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "active")]
    Active,
}

